#!/usr/bin/env bash

set -e

[ "$DEBUG" == 'true' ] && set -x

## Config Defaults
SOURCE_PATH=${SOURCE_PATH-'/data'}
TARGET_PATH=${TARGET_PATH-'/backup'}
DAYS=${DAYS-'30'}

# Command
function uploadBackup {
    # Move files form source to destination
    rsync -az --chmod=u+rw ${SOURCE_PATH}/* ${TARGET_PATH}

    # Remove files from source
    find ${SOURCE_PATH} -mindepth 1 -mtime +${TARGET_PATH} -delete
}

# upload backup
timestart=`date +%s`
CMD=`uploadBackup`
CMD_RET=$?
timetotal=$((`date +%s`-${timestart}))
if [ "${CMD_RET}" -ne 0 ];
then
    echo "Backup Failed during upload. ${timetotal} sec. Msg: ${CMD}"
    exit 1
else
    echo "Backup Completed OK in ${timetotal} sec"
    exit 0
fi
